# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: linting
      run: |
        poetry install
        pip install -U poetry
        pip install isort
        pip install black
        pip install mypy
        pip install flake8
        poetry run isort . --check-only
        poetry run black . --check
        poetry run mypy . --follow-imports=silent
        poetry run flake8 .
    - name: build
      run: |
        echo $(whoami)
        pip install -U poetry
        poetry add coverage="^5.5"
        poetry build
    - name: pytest
      run: |
        poetry install
        CI=1 PYTHONPATH=. poetry run python -mcoverage run --source=cvtools/ -m pytest tests/
        poetry run python -mcoverage report